import { useEffect, useState } from 'react'
import { Link } from '@tanstack/react-router'
import {
  Download, Copy, Check, Mail, CalendarDays, Image as ImageIcon, Palette, Type,
  Megaphone, Newspaper, Send, Rocket, ArrowRight,
} from 'lucide-react'
import { Button, Reveal } from '../components/ui'
import { cn } from '../lib/utils'
import {
  LAUNCH, KEY_MESSAGES, AUDIENCES, BOILERPLATE, ONE_LINERS, SOCIAL_POSTS,
  LAUNCH_EMAIL, PRESS_RELEASE, PRESS_CONTACT,
} from '../lib/launch'

const ASSET_BASE = '/launch'

// Social graphics generated by marketing/scripts/build-assets.mjs.
const GRAPHICS = [
  { file: 'craft-launch-1200x627', name: 'Launch announcement', use: 'LinkedIn / Facebook feed & link share', ratio: 'aspect-[1200/627]' },
  { file: 'craft-launch-1600x900', name: 'Launch announcement 16:9', use: 'X (Twitter) post, presentations', ratio: 'aspect-video' },
  { file: 'craft-save-the-date-1080x1080', name: 'Save the date', use: 'Teaser · Instagram / LinkedIn square', ratio: 'aspect-square' },
  { file: 'craft-now-live-1080x1080', name: 'Now live', use: 'Launch day · Instagram / LinkedIn square', ratio: 'aspect-square' },
  { file: 'craft-paper-compliance-1080x1080', name: 'Key message card', use: 'Post-launch · square feed', ratio: 'aspect-square' },
  { file: 'craft-launch-story-1080x1920', name: 'Story', use: 'Instagram / Facebook / WhatsApp status', ratio: 'aspect-[9/16]' },
  { file: 'craft-linkedin-banner-1584x396', name: 'LinkedIn cover', use: 'Company & team profile banner', ratio: 'aspect-[4/1]' },
  { file: 'craft-x-header-1500x500', name: 'X header', use: 'X (Twitter) profile header', ratio: 'aspect-[3/1]' },
  { file: 'craft-email-header-1200x400', name: 'Email header', use: 'Launch email & newsletters', ratio: 'aspect-[3/1]' },
] as const

const LOGOS = [
  { file: 'craft-lockup-light-bg', name: 'Lockup · light backgrounds', bg: 'bg-white' },
  { file: 'craft-lockup-dark-bg', name: 'Lockup · dark backgrounds', bg: 'bg-emerald-950' },
  { file: 'craft-mark', name: 'Prism shield mark', bg: 'bg-slate-100' },
  { file: 'craft-mark-mono-white', name: 'Mono mark · white', bg: 'bg-emerald-800' },
] as const

const COLORS = [
  { name: 'Deep Emerald', hex: '#022C22', role: 'Primary backgrounds', text: 'text-white' },
  { name: 'Emerald 900', hex: '#064E3B', role: 'Headlines on light', text: 'text-white' },
  { name: 'Emerald 500', hex: '#10B981', role: 'Primary actions', text: 'text-white' },
  { name: 'Mint', hex: '#34D399', role: 'Links & accents on dark', text: 'text-emerald-950' },
  { name: 'Delta Gold', hex: '#FBBF24', role: 'Highlights, dates, CTAs', text: 'text-emerald-950' },
  { name: 'Slate 600', hex: '#475569', role: 'Body text on light', text: 'text-white' },
] as const

const TYPE = [
  { name: 'Playfair Display', role: 'Headlines & wordmark', sample: 'Fiduciary trust, built on evidence.', cls: 'font-display text-2xl font-bold' },
  { name: 'Inter', role: 'Body copy & UI', sample: 'Readiness scoring for G2G, DFI and donor partnerships.', cls: 'font-sans text-base' },
  { name: 'JetBrains Mono', role: 'URLs, codes & data', sample: LAUNCH.displayUrl, cls: 'font-mono text-sm' },
] as const

function useCopy() {
  const [copied, setCopied] = useState<string | null>(null)
  async function copy(id: string, value: string) {
    try {
      await navigator.clipboard.writeText(value)
      setCopied(id)
      setTimeout(() => setCopied(c => (c === id ? null : c)), 1800)
    } catch {
      // Clipboard can be blocked (e.g. insecure context); the text stays selectable.
    }
  }
  return { copied, copy }
}

function CopyButton({ id, value, copied, onCopy, tone = 'light' }: {
  id: string; value: string; copied: string | null; onCopy: (id: string, v: string) => void; tone?: 'light' | 'dark'
}) {
  const done = copied === id
  return (
    <button
      type="button"
      onClick={() => onCopy(id, value)}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-semibold transition-colors',
        tone === 'light'
          ? 'border border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:text-emerald-700'
          : 'border border-emerald-700 bg-emerald-900 text-emerald-100 hover:text-amber-300',
      )}
      aria-label="Copy to clipboard"
    >
      {done ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
      {done ? 'Copied' : 'Copy'}
    </button>
  )
}

function SectionHeading({ icon: Icon, eyebrow, title, desc }: {
  icon: typeof Download; eyebrow: string; title: string; desc?: string
}) {
  return (
    <Reveal>
      <p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-emerald-600">
        <Icon className="h-4 w-4" /> {eyebrow}
      </p>
      <h2 className="mt-2 font-display text-3xl font-bold text-emerald-900 md:text-4xl">{title}</h2>
      {desc && <p className="mt-3 max-w-2xl text-slate-600">{desc}</p>}
    </Reveal>
  )
}

// Days remaining until launch; computed client-side only to avoid SSR/hydration drift.
function useCountdown() {
  const [days, setDays] = useState<number | null>(null)
  useEffect(() => {
    const target = new Date(`${LAUNCH.date}T00:00:00`).getTime()
    setDays(Math.ceil((target - Date.now()) / 86_400_000))
  }, [])
  return days
}

export function LaunchKitPage() {
  const { copied, copy } = useCopy()
  const days = useCountdown()
  const channels = Array.from(new Set(SOCIAL_POSTS.map(p => p.channel)))
  const [channel, setChannel] = useState<string>(channels[0])
  const pressText = [
    PRESS_RELEASE.dateline, '', PRESS_RELEASE.title, '', PRESS_RELEASE.subtitle, '',
    ...PRESS_RELEASE.paragraphs.flatMap(p => [p, '']),
    'About the DiBadili Institute', BOILERPLATE.institute, '',
    `Media contact: ${PRESS_CONTACT.name} · ${PRESS_CONTACT.email} · ${PRESS_CONTACT.web}`,
  ].join('\n')
  const emailText = `Subject: ${LAUNCH_EMAIL.subject}\n\n${LAUNCH_EMAIL.body}`

  return (
    <div className="bg-white">
      {/* Hero */}
      <section className="relative overflow-hidden bg-emerald-950 text-white">
        <div className="pointer-events-none absolute -left-32 -top-32 h-[28rem] w-[28rem] rounded-full bg-emerald-500/20 blur-3xl" />
        <div className="pointer-events-none absolute -bottom-40 right-0 h-96 w-96 rounded-full bg-amber-400/10 blur-3xl" />
        <div className="absolute inset-x-0 top-0 h-1.5 bg-amber-400" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 md:py-24 lg:grid-cols-[1.1fr_1fr]">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-amber-400/60 bg-amber-400/10 px-3 py-1 text-xs font-bold uppercase tracking-widest text-amber-300">
              <CalendarDays className="h-3.5 w-3.5" /> Launching {LAUNCH.dateLong}
            </div>
            <h1 className="mt-6 font-display text-5xl font-bold leading-tight md:text-6xl">
              CRAFT Launch &amp; Press Kit
            </h1>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-emerald-100/80">
              Everything partners, media and champions need to announce CRAFT: social graphics,
              logos, brand guidelines, ready-to-post copy, a launch email and the official press release.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-3">
              <a href={`${ASSET_BASE}/craft-launch-kit.zip`} download>
                <Button size="lg" className="bg-amber-400 text-emerald-950 shadow-amber-400/30 hover:bg-amber-300">
                  <Download className="h-5 w-5" /> Download full kit (.zip)
                </Button>
              </a>
              <a href={`mailto:${LAUNCH.contactEmail}?subject=CRAFT%20launch%20enquiry`}>
                <Button size="lg" variant="ghost" className="text-emerald-100 hover:bg-emerald-900">
                  <Mail className="h-5 w-5" /> {LAUNCH.contactEmail}
                </Button>
              </a>
            </div>
          </div>

          <div className="relative">
            <img
              src={`${ASSET_BASE}/craft-launch-1200x627.png`}
              alt="CRAFT launch announcement graphic"
              className="w-full rounded-2xl border border-emerald-800 shadow-2xl shadow-black/40"
            />
            <div className="absolute -bottom-6 left-6 rounded-xl border border-emerald-800 bg-emerald-900/95 px-5 py-3 shadow-xl backdrop-blur">
              <p className="text-[11px] font-semibold uppercase tracking-widest text-emerald-300">Countdown</p>
              <p className="font-display text-2xl font-bold text-amber-300">
                {days === null ? LAUNCH.dateShort : days > 1 ? `${days} days to go` : days === 1 ? 'Tomorrow' : 'Now live'}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Key messages */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <SectionHeading icon={Megaphone} eyebrow="Key messages" title={LAUNCH.headline}
          desc="Lead with these five points in every channel. Keep the language plain and evidence-first." />
        <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">
          {KEY_MESSAGES.map((m, i) => (
            <Reveal key={m.title} delay={i * 60}>
              <div className="h-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
                <p className="font-mono text-xs font-bold text-amber-500">0{i + 1}</p>
                <h3 className="mt-2 font-display text-lg font-bold text-emerald-900">{m.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-slate-600">{m.body}</p>
              </div>
            </Reveal>
          ))}
        </div>
        <div className="mt-8 grid gap-4 md:grid-cols-4">
          {AUDIENCES.map(a => (
            <div key={a.name} className="rounded-xl bg-emerald-50 p-5">
              <p className="text-sm font-bold text-emerald-900">{a.name}</p>
              <p className="mt-1 text-sm text-emerald-800/80">{a.pitch}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Social graphics */}
      <section className="bg-slate-50 py-20">
        <div className="mx-auto max-w-7xl px-6">
          <SectionHeading icon={ImageIcon} eyebrow="Social graphics" title="Ready-to-post visuals"
            desc="Sized for each platform. Use the PNGs for posting; SVGs are editable sources." />
          <div className="mt-10 columns-1 gap-6 sm:columns-2 lg:columns-3">
            {GRAPHICS.map(g => (
              <div key={g.file} className="mb-6 break-inside-avoid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <a href={`${ASSET_BASE}/${g.file}.png`} target="_blank" rel="noopener noreferrer" className={cn('block bg-emerald-950', g.ratio)}>
                  <img src={`${ASSET_BASE}/${g.file}.png`} alt={g.name} loading="lazy" className="h-full w-full object-cover" />
                </a>
                <div className="flex items-start justify-between gap-3 p-4">
                  <div>
                    <p className="font-semibold text-emerald-900">{g.name}</p>
                    <p className="text-xs text-slate-500">{g.use}</p>
                    <p className="mt-1 font-mono text-[11px] text-slate-400">{g.file.split('-').pop()}</p>
                  </div>
                  <div className="flex shrink-0 gap-1.5">
                    <a href={`${ASSET_BASE}/${g.file}.png`} download className="rounded-md bg-emerald-500 px-2.5 py-1 text-xs font-semibold text-white hover:bg-emerald-600">PNG</a>
                    <a href={`${ASSET_BASE}/${g.file}.svg`} download className="rounded-md border border-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-600 hover:border-emerald-300">SVG</a>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social copy */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <SectionHeading icon={Send} eyebrow="Launch copy" title="Posts for every phase"
          desc="Teaser three days before launch, the announcement on launch day, and a follow-up during launch week." />
        <div className="mt-8 flex flex-wrap gap-2">
          {channels.map(c => (
            <button
              key={c}
              type="button"
              onClick={() => setChannel(c)}
              className={cn(
                'rounded-full px-4 py-1.5 text-sm font-semibold transition-colors',
                c === channel ? 'bg-emerald-900 text-white' : 'bg-slate-100 text-slate-600 hover:bg-emerald-50 hover:text-emerald-800',
              )}
            >
              {c}
            </button>
          ))}
        </div>
        <div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
          {SOCIAL_POSTS.filter(p => p.channel === channel).map((p, i) => {
            const id = `post-${p.channel}-${i}`
            return (
              <div key={id} className="flex flex-col rounded-2xl border border-slate-200 bg-white shadow-sm">
                <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3">
                  <span className="text-xs font-bold uppercase tracking-wider text-amber-600">{p.phase}</span>
                  <CopyButton id={id} value={p.text} copied={copied} onCopy={copy} />
                </div>
                <p className="flex-1 whitespace-pre-line px-5 py-4 text-sm leading-relaxed text-slate-700">{p.text}</p>
              </div>
            )
          })}
        </div>

        <div className="mt-12 grid gap-6 lg:grid-cols-2">
          <div className="rounded-2xl border border-slate-200 p-6">
            <h3 className="font-display text-xl font-bold text-emerald-900">One-liners</h3>
            <ul className="mt-4 space-y-3">
              {ONE_LINERS.map((l, i) => (
                <li key={l} className="flex items-start justify-between gap-3 text-sm text-slate-700">
                  <span>{l}</span>
                  <CopyButton id={`line-${i}`} value={l} copied={copied} onCopy={copy} />
                </li>
              ))}
            </ul>
            <p className="mt-5 text-xs font-semibold uppercase tracking-wider text-slate-400">Hashtags</p>
            <div className="mt-2 flex flex-wrap items-center gap-2">
              {LAUNCH.hashtags.map(h => (
                <span key={h} className="rounded-full bg-emerald-50 px-3 py-1 font-mono text-xs text-emerald-700">{h}</span>
              ))}
              <CopyButton id="tags" value={LAUNCH.hashtags.join(' ')} copied={copied} onCopy={copy} />
            </div>
          </div>
          <div className="rounded-2xl border border-slate-200 p-6">
            <h3 className="font-display text-xl font-bold text-emerald-900">Boilerplate</h3>
            {([
              ['Short', BOILERPLATE.short],
              ['Medium', BOILERPLATE.medium],
              ['About the DiBadili Institute', BOILERPLATE.institute],
            ] as const).map(([label, body]) => (
              <div key={label} className="mt-4">
                <div className="flex items-center justify-between">
                  <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p>
                  <CopyButton id={`bp-${label}`} value={body} copied={copied} onCopy={copy} />
                </div>
                <p className="mt-1 text-sm leading-relaxed text-slate-700">{body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Email + press release */}
      <section className="bg-slate-50 py-20">
        <div className="mx-auto grid max-w-7xl gap-8 px-6 lg:grid-cols-2">
          <div>
            <SectionHeading icon={Mail} eyebrow="Launch email" title="Announce it to your network" />
            <div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
              <img src={`${ASSET_BASE}/craft-email-header-1200x400.png`} alt="CRAFT launch email header" className="w-full" />
              <div className="p-6">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Subject</p>
                    <p className="font-semibold text-emerald-900">{LAUNCH_EMAIL.subject}</p>
                    <p className="mt-1 text-xs text-slate-500">Preheader: {LAUNCH_EMAIL.preheader}</p>
                  </div>
                  <CopyButton id="email" value={emailText} copied={copied} onCopy={copy} />
                </div>
                <p className="mt-5 whitespace-pre-line text-sm leading-relaxed text-slate-700">{LAUNCH_EMAIL.body}</p>
              </div>
            </div>
          </div>
          <div>
            <SectionHeading icon={Newspaper} eyebrow="Press release" title="For media & partners" />
            <article className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
              <div className="flex items-center justify-between gap-3">
                <p className="font-mono text-xs font-bold text-amber-600">{PRESS_RELEASE.dateline}</p>
                <CopyButton id="press" value={pressText} copied={copied} onCopy={copy} />
              </div>
              <h3 className="mt-4 font-display text-2xl font-bold leading-snug text-emerald-900">{PRESS_RELEASE.title}</h3>
              <p className="mt-3 italic text-slate-600">{PRESS_RELEASE.subtitle}</p>
              <div className="mt-5 space-y-4 text-sm leading-relaxed text-slate-700">
                {PRESS_RELEASE.paragraphs.map(p => <p key={p.slice(0, 40)}>{p}</p>)}
              </div>
              <h4 className="mt-6 text-sm font-bold text-emerald-900">About the DiBadili Institute</h4>
              <p className="mt-1 text-sm leading-relaxed text-slate-700">{BOILERPLATE.institute}</p>
              <p className="mt-6 border-t border-slate-100 pt-4 text-sm text-slate-600">
                <span className="font-semibold text-emerald-900">Media contact:</span> {PRESS_CONTACT.name} ·{' '}
                <a href={`mailto:${PRESS_CONTACT.email}`} className="font-medium text-emerald-700 hover:underline">{PRESS_CONTACT.email}</a>
              </p>
              <p className="mt-4 text-center text-slate-400">###</p>
            </article>
          </div>
        </div>
      </section>

      {/* Brand kit */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <SectionHeading icon={Palette} eyebrow="Brand kit" title="Logos, colour & type"
          desc="Use the lockup wherever space allows; use the shield mark alone for avatars and small sizes. Keep clear space equal to the height of the delta around the mark." />
        <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {LOGOS.map(l => (
            <div key={l.file} className="overflow-hidden rounded-2xl border border-slate-200">
              <div className={cn('flex h-40 items-center justify-center p-6', l.bg)}>
                <img src={`${ASSET_BASE}/${l.file}.png`} alt={l.name} className="max-h-full max-w-full" loading="lazy" />
              </div>
              <div className="flex items-center justify-between gap-2 p-4">
                <p className="text-sm font-semibold text-emerald-900">{l.name}</p>
                <div className="flex gap-1.5">
                  <a href={`${ASSET_BASE}/${l.file}.png`} download className="rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-white hover:bg-emerald-600">PNG</a>
                  <a href={`${ASSET_BASE}/${l.file}.svg`} download className="rounded-md border border-slate-200 px-2 py-1 text-xs font-semibold text-slate-600 hover:border-emerald-300">SVG</a>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
          {COLORS.map(c => (
            <button
              key={c.hex}
              type="button"
              onClick={() => copy(`color-${c.hex}`, c.hex)}
              className="group overflow-hidden rounded-2xl border border-slate-200 text-left transition-shadow hover:shadow-md"
            >
              <div className={cn('flex h-24 items-end p-3 font-mono text-xs font-bold', c.text)} style={{ backgroundColor: c.hex }}>
                {copied === `color-${c.hex}` ? 'Copied!' : c.hex}
              </div>
              <div className="p-3">
                <p className="text-sm font-semibold text-emerald-900">{c.name}</p>
                <p className="text-xs text-slate-500">{c.role}</p>
              </div>
            </button>
          ))}
        </div>

        <div className="mt-12 grid gap-5 md:grid-cols-3">
          {TYPE.map(t => (
            <div key={t.name} className="rounded-2xl border border-slate-200 p-6">
              <p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-400">
                <Type className="h-3.5 w-3.5" /> {t.role}
              </p>
              <p className="mt-1 font-semibold text-emerald-900">{t.name}</p>
              <p className={cn('mt-4 text-slate-800', t.cls)}>{t.sample}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 grid gap-5 md:grid-cols-2">
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6">
            <h3 className="font-bold text-emerald-900">Do</h3>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm text-emerald-900/80">
              <li>Write the name as <strong>CRAFT</strong> (all caps), with the full name on first mention.</li>
              <li>Pair Deep Emerald backgrounds with white headlines and gold highlights.</li>
              <li>Always include the URL <span className="font-mono">{LAUNCH.displayUrl}</span>.</li>
              <li>Credit the DiBadili Institute as the publisher.</li>
            </ul>
          </div>
          <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6">
            <h3 className="font-bold text-rose-900">Don&apos;t</h3>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm text-rose-900/80">
              <li>Recolour, stretch, rotate or add effects to the shield mark.</li>
              <li>Place the full-colour mark on busy photos or mid-tone greens.</li>
              <li>Use gold for long body text; reserve it for accents.</li>
              <li>Use legacy names such as G2G-ICGMT in launch materials.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Contact CTA */}
      <section className="bg-emerald-900">
        <div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-6 py-14 md:flex-row md:items-center">
          <div>
            <p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-amber-400">
              <Rocket className="h-4 w-4" /> Media &amp; partnership enquiries
            </p>
            <p className="mt-2 font-display text-3xl font-bold text-white">Interviews, co-announcements or custom assets?</p>
            <a href={`mailto:${LAUNCH.contactEmail}`} className="mt-2 inline-block font-mono text-emerald-200 hover:text-amber-300">
              {LAUNCH.contactEmail}
            </a>
          </div>
          <div className="flex flex-wrap gap-3">
            <a href={`mailto:${LAUNCH.contactEmail}?subject=CRAFT%20launch%20enquiry`}>
              <Button size="lg" className="bg-amber-400 text-emerald-950 shadow-amber-400/30 hover:bg-amber-300">
                <Mail className="h-5 w-5" /> Contact the launch team
              </Button>
            </a>
            <Link to="/demo">
              <Button size="lg" variant="ghost" className="text-emerald-100 hover:bg-emerald-800">
                Try the demo <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
