import { Scale, ShieldAlert, FileText, AlertTriangle, Ban, Globe } from 'lucide-react'
import { Reveal } from '../components/ui'
import { BRAND } from '../lib/data'

// Last substantive revision of these terms. Update when the text changes.
const EFFECTIVE_DATE = 'June 7, 2026'

interface Clause {
  icon: typeof Scale
  title: string
  body: React.ReactNode
}

const CLAUSES: Clause[] = [
  {
    icon: FileText,
    title: '1. Acceptance of these Terms',
    body: (
      <>
        By accessing or using {BRAND.product} ({BRAND.framework}), the “Service”, operated by the{' '}
        {BRAND.institute}, you agree to be bound by these Terms of Service. If you do not agree with any
        part of these terms, you must not use the Service. These terms apply to all visitors, demo users,
        registered institutions, and team members invited to a workspace.
      </>
    ),
  },
  {
    icon: Globe,
    title: '2. Nature of the Service',
    body: (
      <>
        {BRAND.product} is a self-assessment and capacity-readiness toolkit. It produces indicative
        readiness indications, scores, and capacity-development guidance based on the information you
        provide. The Service is an informational and diagnostic aid only. It is{' '}
        <strong>not</strong> an accreditation, certification, audit, legal, financial, or professional
        advisory service, and it does not guarantee eligibility for, or access to, any funding, grant,
        partnership, or program.
      </>
    ),
  },
  {
    icon: ShieldAlert,
    title: '3. No Warranties',
    body: (
      <>
        The Service is provided strictly on an <strong>“as is”</strong> and{' '}
        <strong>“as available”</strong> basis, without warranties of any kind, whether express, implied,
        statutory, or otherwise, including without limitation any implied warranties of merchantability,
        fitness for a particular purpose, accuracy, non-infringement, or uninterrupted or error-free
        operation. The {BRAND.institute} does not warrant that the results, scores, or recommendations
        generated by the Service are accurate, complete, reliable, or suitable for any particular
        decision or purpose.
      </>
    ),
  },
  {
    icon: Ban,
    title: '4. Limitation of Liability',
    body: (
      <>
        To the maximum extent permitted by applicable law, the {BRAND.institute}, its affiliates,
        partners, officers, employees, contributors, and licensors shall <strong>not</strong> be liable
        for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any
        loss of profits, revenue, funding, data, goodwill, or other intangible losses, arising out of or
        in connection with your access to, use of, or inability to use the Service, whether based in
        contract, tort (including negligence), strict liability, or any other legal theory, and whether
        or not the {BRAND.institute} has been advised of the possibility of such damages. In no event
        shall the total aggregate liability of the {BRAND.institute} to you for all claims relating to
        the Service exceed one hundred United States dollars (USD&nbsp;$100), or the amount you paid to
        use the Service in the twelve months preceding the claim, whichever is greater. Some jurisdictions
        do not allow certain limitations; where a limitation is not permitted, the liability of the
        {' '}{BRAND.institute} is limited to the smallest amount permitted by law.
      </>
    ),
  },
  {
    icon: AlertTriangle,
    title: '5. Your Responsibilities & Indemnity',
    body: (
      <>
        You are solely responsible for the data you enter, the decisions you make, and the actions you
        take based on output from the Service. You agree to use the Service in compliance with all
        applicable laws and not to rely on it as a substitute for independent professional judgment. You
        agree to indemnify and hold harmless the {BRAND.institute} and its contributors from any claims,
        damages, liabilities, and expenses arising from your use of the Service or your violation of these
        terms.
      </>
    ),
  },
  {
    icon: Scale,
    title: '6. Data, Ownership & Open-Source Licensing',
    body: (
      <>
        Data you enter into your own workspace remains yours; you retain full ownership of your
        institutional data and the {BRAND.institute} claims no proprietary rights over it. The {BRAND.product}{' '}
        software is distributed under GPL-3.0 and the underlying assessment methodology under
        CC&nbsp;BY-SA&nbsp;4.0. Demo sessions use illustrative sample data, are fully isolated, and are not
        retained. These open-source licenses govern the software and methodology only; they do not grant
        any rights over your institutional data.
      </>
    ),
  },
  {
    icon: FileText,
    title: '7. Changes & Governing Terms',
    body: (
      <>
        The {BRAND.institute} may revise these terms at any time by updating this page; continued use of
        the Service after changes take effect constitutes acceptance of the revised terms. If any
        provision of these terms is found unenforceable, the remaining provisions remain in full force.
        For questions about these terms, contact{' '}
        <a
          href={`mailto:${BRAND.contactEmail}`}
          className="font-semibold text-emerald-700 underline-offset-2 hover:underline"
        >
          {BRAND.contactEmail}
        </a>
        .
      </>
    ),
  },
]

export function TermsPage() {
  return (
    <div>
      <section className="bg-gradient-to-br from-emerald-900 to-slate-900 py-20 text-white">
        <div className="mx-auto max-w-4xl px-6">
          <p className="text-sm font-semibold uppercase tracking-wider text-amber-400">Legal</p>
          <h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Terms of Service</h1>
          <p className="mt-5 max-w-2xl text-base leading-relaxed text-slate-300 sm:text-lg">
            The terms that govern your use of {BRAND.product} ({BRAND.framework}). They explain what the
            Service is, the limits of our liability, and your responsibilities as a user.
          </p>
          <p className="mt-4 text-xs text-slate-400">Effective date: {EFFECTIVE_DATE}</p>
        </div>
      </section>

      <section className="mx-auto max-w-4xl px-6 py-16">
        <Reveal>
          <div className="mb-8 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-relaxed text-amber-900">
            <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-500" />
            <p>
              <strong>Important:</strong> {BRAND.product} provides indicative self-assessment results for
              informational purposes only. It is not a guarantee of funding, accreditation, or compliance,
              and the {BRAND.institute}’s liability for its use is strictly limited as set out below.
            </p>
          </div>
        </Reveal>

        <div className="space-y-5">
          {CLAUSES.map((c, i) => {
            const Icon = c.icon
            return (
              <Reveal key={c.title} delay={i * 60}>
                <div className="flex items-start gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <h2 className="font-display text-lg font-bold text-emerald-900 sm:text-xl">{c.title}</h2>
                    <p className="mt-2 text-sm leading-relaxed text-slate-600 sm:text-[15px]">{c.body}</p>
                  </div>
                </div>
              </Reveal>
            )
          })}
        </div>

        <p className="mt-10 text-center text-xs text-slate-400">
          {BRAND.footer}
        </p>
      </section>
    </div>
  )
}
