// ============================================================================
// CRAFT v4.0 — Offline status banner + PWA bootstrap
// ----------------------------------------------------------------------------
// A single, non-intrusive floating pill (bottom-right) that tells field users
// what the app is doing with their data: working offline, syncing to the secure
// vault, or all-clear. It also boots the offline subsystem for the tab:
//   • registers the Workbox service worker generated by vite-plugin-pwa
//   • starts the SyncEngine so queued writes drain when a signal returns
//
// Client-only: renders nothing during SSR and until mounted, so it never
// mismatches the server HTML. Colours follow the DiBadili palette — rose for
// offline, amber for syncing, emerald for synced.
// ============================================================================

import { useEffect, useState } from 'react'
import { WifiOff, RefreshCw, CheckCircle2, AlertTriangle } from 'lucide-react'
import { syncEngine, type SyncState } from '../lib/offline/sync-engine'

export function OfflineBanner() {
  const [mounted, setMounted] = useState(false)
  const [online, setOnline] = useState(true)
  const [sync, setSync] = useState<SyncState>(syncEngine.getState())
  // Briefly surface an emerald "synced" confirmation after a drain completes.
  const [justSynced, setJustSynced] = useState(false)

  useEffect(() => {
    setMounted(true)
    setOnline(navigator.onLine)

    // Register the service worker (generated at build by vite-plugin-pwa).
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker
        .register('/sw.js', { scope: '/' })
        .catch(err => console.warn('[pwa] service worker registration failed', err))
    }

    // Boot the queue drainer and mirror its state into the banner.
    syncEngine.start()
    const unsub = syncEngine.subscribe(setSync)

    const onOnline = () => setOnline(true)
    const onOffline = () => setOnline(false)
    window.addEventListener('online', onOnline)
    window.addEventListener('offline', onOffline)

    return () => {
      unsub()
      window.removeEventListener('online', onOnline)
      window.removeEventListener('offline', onOffline)
    }
  }, [])

  // Flash the synced confirmation for a moment whenever a sync finishes clean.
  useEffect(() => {
    if (sync.status === 'idle' && sync.lastSyncedAt) {
      setJustSynced(true)
      const t = setTimeout(() => setJustSynced(false), 3000)
      return () => clearTimeout(t)
    }
  }, [sync.status, sync.lastSyncedAt])

  if (!mounted) return null

  const isOffline = !online
  const isSyncing = sync.status === 'syncing'
  const isError = sync.status === 'error'

  // Nothing worth interrupting the user for: online, idle, nothing pending, and
  // no recent-sync flash to show.
  if (!isOffline && !isSyncing && !isError && !justSynced) return null

  let tone: string
  let icon: React.ReactNode
  let label: string

  if (isOffline) {
    tone = 'border-rose-400/60 bg-rose-600 text-white'
    icon = <WifiOff className="h-4 w-4 shrink-0" />
    label = 'Offline Mode. Changes saved locally.'
  } else if (isSyncing) {
    tone = 'border-amber-300/60 bg-amber-400 text-amber-950'
    icon = <RefreshCw className="h-4 w-4 shrink-0 animate-spin" />
    label = 'Syncing data to secure vault...'
  } else if (isError) {
    tone = 'border-rose-400/60 bg-rose-600 text-white'
    icon = <AlertTriangle className="h-4 w-4 shrink-0" />
    label = 'Sync interrupted. Will retry automatically.'
  } else {
    tone = 'border-emerald-400/60 bg-emerald-500 text-white'
    icon = <CheckCircle2 className="h-4 w-4 shrink-0" />
    label = 'All changes synced to secure vault.'
  }

  const pending = sync.pending
  return (
    <div
      role="status"
      aria-live="polite"
      className={`fixed bottom-4 right-4 z-[60] flex items-center gap-2.5 rounded-full border px-4 py-2.5 text-sm font-medium shadow-lg backdrop-blur transition-all ${tone}`}
    >
      {icon}
      <span className="font-sans">{label}</span>
      {pending > 0 && (isOffline || isSyncing) && (
        <span className="ml-0.5 rounded-full bg-black/15 px-2 py-0.5 font-mono text-xs tabular-nums">
          {pending} queued
        </span>
      )}
    </div>
  )
}
