/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CipRouteImport } from './routes/cip'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataRoomRouteImport } from './routes/data-room'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FinanceTriangulationRouteImport } from './routes/finance-triangulation'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InformalEconomyRouteImport } from './routes/informal-economy'
import { Route as InstituteRouteImport } from './routes/institute'
import { Route as IssbDisclosuresRouteImport } from './routes/issb-disclosures'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ObligationsRouteImport } from './routes/obligations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as PreAssessmentRouteImport } from './routes/pre-assessment'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegulatoryComplianceRouteImport } from './routes/regulatory-compliance'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WallboardRouteImport } from './routes/wallboard'
import { Route as AcceptTokenRouteImport } from './routes/accept.$token'
import { Route as AdminPortfolioRouteImport } from './routes/admin_.portfolio'
import { Route as AssessmentFrameworkIdRouteImport } from './routes/assessment.$frameworkId'
import { Route as DashboardTrustDeltaRouteImport } from './routes/dashboard_.trust-delta'
import { Route as AppOrgAuditLogRouteImport } from './routes/app.org.audit-log'
import { Route as AppOrgMembersRouteImport } from './routes/app.org.members'
import { Route as AppOrgSettingsRouteImport } from './routes/app.org.settings'
import { Route as AppWorkspacesIndexRouteImport } from './routes/app.workspaces.index'
import { Route as AppWorkspacesWorkspaceIdComplianceDashboardRouteImport } from './routes/app.workspaces.$workspaceId.compliance-dashboard'
import { Route as AppWorkspacesWorkspaceIdDashboardRouteImport } from './routes/app.workspaces.$workspaceId.dashboard'
import { Route as AppWorkspacesWorkspaceIdSupportBotRouteImport } from './routes/app.workspaces.$workspaceId.support-bot'
import { Route as AppWorkspacesWorkspaceIdSupportIssuesRouteImport } from './routes/app.workspaces.$workspaceId.support-issues'
import { Route as AppWorkspacesWorkspaceIdActionsIndexRouteImport } from './routes/app.workspaces.$workspaceId.actions.index'
import { Route as AppWorkspacesWorkspaceIdActionsCapIdRouteImport } from './routes/app.workspaces.$workspaceId.actions.$capId'
import { Route as AppWorkspacesWorkspaceIdEsgFrameworksRouteImport } from './routes/app.workspaces.$workspaceId.esg.frameworks'
import { Route as AppWorkspacesWorkspaceIdEsgRequirementsRouteImport } from './routes/app.workspaces.$workspaceId.esg.requirements'
import { Route as AppWorkspacesWorkspaceIdEsgRoadmapRouteImport } from './routes/app.workspaces.$workspaceId.esg.roadmap'
import { Route as AppWorkspacesWorkspaceIdEvidenceIndexRouteImport } from './routes/app.workspaces.$workspaceId.evidence.index'
import { Route as AppWorkspacesWorkspaceIdEvidenceEvidenceIdRouteImport } from './routes/app.workspaces.$workspaceId.evidence.$evidenceId'
import { Route as AppWorkspacesWorkspaceIdReportsIndexRouteImport } from './routes/app.workspaces.$workspaceId.reports.index'
import { Route as AppWorkspacesWorkspaceIdReportsReportIdRouteImport } from './routes/app.workspaces.$workspaceId.reports.$reportId'
import { Route as AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRouteImport } from './routes/app.workspaces.$workspaceId.esg.implementation.$requirementId'
import { Route as AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRouteImport } from './routes/app.workspaces.$workspaceId.governance.assessments.index'
import { Route as AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRouteImport } from './routes/app.workspaces.$workspaceId.governance.assessments.$assessmentId.index'
import { Route as AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRouteImport } from './routes/app.workspaces.$workspaceId.governance.assessments.$assessmentId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CipRoute = CipRouteImport.update({
  id: '/cip',
  path: '/cip',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoomRoute = DataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTriangulationRoute = FinanceTriangulationRouteImport.update({
  id: '/finance-triangulation',
  path: '/finance-triangulation',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InformalEconomyRoute = InformalEconomyRouteImport.update({
  id: '/informal-economy',
  path: '/informal-economy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteRoute = InstituteRouteImport.update({
  id: '/institute',
  path: '/institute',
  getParentRoute: () => rootRouteImport,
} as any)
const IssbDisclosuresRoute = IssbDisclosuresRouteImport.update({
  id: '/issb-disclosures',
  path: '/issb-disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligationsRoute = ObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const PreAssessmentRoute = PreAssessmentRouteImport.update({
  id: '/pre-assessment',
  path: '/pre-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryComplianceRoute = RegulatoryComplianceRouteImport.update({
  id: '/regulatory-compliance',
  path: '/regulatory-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboardRoute = WallboardRouteImport.update({
  id: '/wallboard',
  path: '/wallboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTokenRoute = AcceptTokenRouteImport.update({
  id: '/accept/$token',
  path: '/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/admin_/portfolio',
  path: '/admin/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentFrameworkIdRoute = AssessmentFrameworkIdRouteImport.update({
  id: '/$frameworkId',
  path: '/$frameworkId',
  getParentRoute: () => AssessmentRoute,
} as any)
const DashboardTrustDeltaRoute = DashboardTrustDeltaRouteImport.update({
  id: '/dashboard_/trust-delta',
  path: '/dashboard/trust-delta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgAuditLogRoute = AppOrgAuditLogRouteImport.update({
  id: '/app/org/audit-log',
  path: '/app/org/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgMembersRoute = AppOrgMembersRouteImport.update({
  id: '/app/org/members',
  path: '/app/org/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSettingsRoute = AppOrgSettingsRouteImport.update({
  id: '/app/org/settings',
  path: '/app/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/app/workspaces/',
  path: '/app/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesWorkspaceIdComplianceDashboardRoute =
  AppWorkspacesWorkspaceIdComplianceDashboardRouteImport.update({
    id: '/app/workspaces/$workspaceId/compliance-dashboard',
    path: '/app/workspaces/$workspaceId/compliance-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdDashboardRoute =
  AppWorkspacesWorkspaceIdDashboardRouteImport.update({
    id: '/app/workspaces/$workspaceId/dashboard',
    path: '/app/workspaces/$workspaceId/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdSupportBotRoute =
  AppWorkspacesWorkspaceIdSupportBotRouteImport.update({
    id: '/app/workspaces/$workspaceId/support-bot',
    path: '/app/workspaces/$workspaceId/support-bot',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdSupportIssuesRoute =
  AppWorkspacesWorkspaceIdSupportIssuesRouteImport.update({
    id: '/app/workspaces/$workspaceId/support-issues',
    path: '/app/workspaces/$workspaceId/support-issues',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdActionsIndexRoute =
  AppWorkspacesWorkspaceIdActionsIndexRouteImport.update({
    id: '/app/workspaces/$workspaceId/actions/',
    path: '/app/workspaces/$workspaceId/actions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdActionsCapIdRoute =
  AppWorkspacesWorkspaceIdActionsCapIdRouteImport.update({
    id: '/app/workspaces/$workspaceId/actions/$capId',
    path: '/app/workspaces/$workspaceId/actions/$capId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEsgFrameworksRoute =
  AppWorkspacesWorkspaceIdEsgFrameworksRouteImport.update({
    id: '/app/workspaces/$workspaceId/esg/frameworks',
    path: '/app/workspaces/$workspaceId/esg/frameworks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEsgRequirementsRoute =
  AppWorkspacesWorkspaceIdEsgRequirementsRouteImport.update({
    id: '/app/workspaces/$workspaceId/esg/requirements',
    path: '/app/workspaces/$workspaceId/esg/requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEsgRoadmapRoute =
  AppWorkspacesWorkspaceIdEsgRoadmapRouteImport.update({
    id: '/app/workspaces/$workspaceId/esg/roadmap',
    path: '/app/workspaces/$workspaceId/esg/roadmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEvidenceIndexRoute =
  AppWorkspacesWorkspaceIdEvidenceIndexRouteImport.update({
    id: '/app/workspaces/$workspaceId/evidence/',
    path: '/app/workspaces/$workspaceId/evidence/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute =
  AppWorkspacesWorkspaceIdEvidenceEvidenceIdRouteImport.update({
    id: '/app/workspaces/$workspaceId/evidence/$evidenceId',
    path: '/app/workspaces/$workspaceId/evidence/$evidenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdReportsIndexRoute =
  AppWorkspacesWorkspaceIdReportsIndexRouteImport.update({
    id: '/app/workspaces/$workspaceId/reports/',
    path: '/app/workspaces/$workspaceId/reports/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdReportsReportIdRoute =
  AppWorkspacesWorkspaceIdReportsReportIdRouteImport.update({
    id: '/app/workspaces/$workspaceId/reports/$reportId',
    path: '/app/workspaces/$workspaceId/reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute =
  AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRouteImport.update({
    id: '/app/workspaces/$workspaceId/esg/implementation/$requirementId',
    path: '/app/workspaces/$workspaceId/esg/implementation/$requirementId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute =
  AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRouteImport.update({
    id: '/app/workspaces/$workspaceId/governance/assessments/',
    path: '/app/workspaces/$workspaceId/governance/assessments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute =
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRouteImport.update(
    {
      id: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/',
      path: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute =
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRouteImport.update(
    {
      id: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review',
      path: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cip': typeof CipRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-room': typeof DataRoomRoute
  '/demo': typeof DemoRoute
  '/evidence': typeof EvidenceRoute
  '/finance-triangulation': typeof FinanceTriangulationRoute
  '/findings': typeof FindingsRoute
  '/frameworks': typeof FrameworksRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/informal-economy': typeof InformalEconomyRoute
  '/institute': typeof InstituteRoute
  '/issb-disclosures': typeof IssbDisclosuresRoute
  '/launch': typeof LaunchRoute
  '/methodology': typeof MethodologyRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/open-source': typeof OpenSourceRoute
  '/pre-assessment': typeof PreAssessmentRoute
  '/privacy': typeof PrivacyRoute
  '/regulatory-compliance': typeof RegulatoryComplianceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vaults': typeof VaultsRoute
  '/verify': typeof VerifyRoute
  '/wallboard': typeof WallboardRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/assessment/$frameworkId': typeof AssessmentFrameworkIdRoute
  '/dashboard/trust-delta': typeof DashboardTrustDeltaRoute
  '/app/org/audit-log': typeof AppOrgAuditLogRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/workspaces/': typeof AppWorkspacesIndexRoute
  '/app/workspaces/$workspaceId/compliance-dashboard': typeof AppWorkspacesWorkspaceIdComplianceDashboardRoute
  '/app/workspaces/$workspaceId/dashboard': typeof AppWorkspacesWorkspaceIdDashboardRoute
  '/app/workspaces/$workspaceId/support-bot': typeof AppWorkspacesWorkspaceIdSupportBotRoute
  '/app/workspaces/$workspaceId/support-issues': typeof AppWorkspacesWorkspaceIdSupportIssuesRoute
  '/app/workspaces/$workspaceId/actions/$capId': typeof AppWorkspacesWorkspaceIdActionsCapIdRoute
  '/app/workspaces/$workspaceId/esg/frameworks': typeof AppWorkspacesWorkspaceIdEsgFrameworksRoute
  '/app/workspaces/$workspaceId/esg/requirements': typeof AppWorkspacesWorkspaceIdEsgRequirementsRoute
  '/app/workspaces/$workspaceId/esg/roadmap': typeof AppWorkspacesWorkspaceIdEsgRoadmapRoute
  '/app/workspaces/$workspaceId/evidence/$evidenceId': typeof AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute
  '/app/workspaces/$workspaceId/reports/$reportId': typeof AppWorkspacesWorkspaceIdReportsReportIdRoute
  '/app/workspaces/$workspaceId/actions/': typeof AppWorkspacesWorkspaceIdActionsIndexRoute
  '/app/workspaces/$workspaceId/evidence/': typeof AppWorkspacesWorkspaceIdEvidenceIndexRoute
  '/app/workspaces/$workspaceId/reports/': typeof AppWorkspacesWorkspaceIdReportsIndexRoute
  '/app/workspaces/$workspaceId/esg/implementation/$requirementId': typeof AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute
  '/app/workspaces/$workspaceId/governance/assessments/': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cip': typeof CipRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-room': typeof DataRoomRoute
  '/demo': typeof DemoRoute
  '/evidence': typeof EvidenceRoute
  '/finance-triangulation': typeof FinanceTriangulationRoute
  '/findings': typeof FindingsRoute
  '/frameworks': typeof FrameworksRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/informal-economy': typeof InformalEconomyRoute
  '/institute': typeof InstituteRoute
  '/issb-disclosures': typeof IssbDisclosuresRoute
  '/launch': typeof LaunchRoute
  '/methodology': typeof MethodologyRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/open-source': typeof OpenSourceRoute
  '/pre-assessment': typeof PreAssessmentRoute
  '/privacy': typeof PrivacyRoute
  '/regulatory-compliance': typeof RegulatoryComplianceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vaults': typeof VaultsRoute
  '/verify': typeof VerifyRoute
  '/wallboard': typeof WallboardRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/assessment/$frameworkId': typeof AssessmentFrameworkIdRoute
  '/dashboard/trust-delta': typeof DashboardTrustDeltaRoute
  '/app/org/audit-log': typeof AppOrgAuditLogRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/workspaces': typeof AppWorkspacesIndexRoute
  '/app/workspaces/$workspaceId/compliance-dashboard': typeof AppWorkspacesWorkspaceIdComplianceDashboardRoute
  '/app/workspaces/$workspaceId/dashboard': typeof AppWorkspacesWorkspaceIdDashboardRoute
  '/app/workspaces/$workspaceId/support-bot': typeof AppWorkspacesWorkspaceIdSupportBotRoute
  '/app/workspaces/$workspaceId/support-issues': typeof AppWorkspacesWorkspaceIdSupportIssuesRoute
  '/app/workspaces/$workspaceId/actions/$capId': typeof AppWorkspacesWorkspaceIdActionsCapIdRoute
  '/app/workspaces/$workspaceId/esg/frameworks': typeof AppWorkspacesWorkspaceIdEsgFrameworksRoute
  '/app/workspaces/$workspaceId/esg/requirements': typeof AppWorkspacesWorkspaceIdEsgRequirementsRoute
  '/app/workspaces/$workspaceId/esg/roadmap': typeof AppWorkspacesWorkspaceIdEsgRoadmapRoute
  '/app/workspaces/$workspaceId/evidence/$evidenceId': typeof AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute
  '/app/workspaces/$workspaceId/reports/$reportId': typeof AppWorkspacesWorkspaceIdReportsReportIdRoute
  '/app/workspaces/$workspaceId/actions': typeof AppWorkspacesWorkspaceIdActionsIndexRoute
  '/app/workspaces/$workspaceId/evidence': typeof AppWorkspacesWorkspaceIdEvidenceIndexRoute
  '/app/workspaces/$workspaceId/reports': typeof AppWorkspacesWorkspaceIdReportsIndexRoute
  '/app/workspaces/$workspaceId/esg/implementation/$requirementId': typeof AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute
  '/app/workspaces/$workspaceId/governance/assessments': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cip': typeof CipRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/data-room': typeof DataRoomRoute
  '/demo': typeof DemoRoute
  '/evidence': typeof EvidenceRoute
  '/finance-triangulation': typeof FinanceTriangulationRoute
  '/findings': typeof FindingsRoute
  '/frameworks': typeof FrameworksRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/informal-economy': typeof InformalEconomyRoute
  '/institute': typeof InstituteRoute
  '/issb-disclosures': typeof IssbDisclosuresRoute
  '/launch': typeof LaunchRoute
  '/methodology': typeof MethodologyRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/open-source': typeof OpenSourceRoute
  '/pre-assessment': typeof PreAssessmentRoute
  '/privacy': typeof PrivacyRoute
  '/regulatory-compliance': typeof RegulatoryComplianceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vaults': typeof VaultsRoute
  '/verify': typeof VerifyRoute
  '/wallboard': typeof WallboardRoute
  '/accept/$token': typeof AcceptTokenRoute
  '/admin_/portfolio': typeof AdminPortfolioRoute
  '/assessment/$frameworkId': typeof AssessmentFrameworkIdRoute
  '/dashboard_/trust-delta': typeof DashboardTrustDeltaRoute
  '/app/org/audit-log': typeof AppOrgAuditLogRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/workspaces/': typeof AppWorkspacesIndexRoute
  '/app/workspaces/$workspaceId/compliance-dashboard': typeof AppWorkspacesWorkspaceIdComplianceDashboardRoute
  '/app/workspaces/$workspaceId/dashboard': typeof AppWorkspacesWorkspaceIdDashboardRoute
  '/app/workspaces/$workspaceId/support-bot': typeof AppWorkspacesWorkspaceIdSupportBotRoute
  '/app/workspaces/$workspaceId/support-issues': typeof AppWorkspacesWorkspaceIdSupportIssuesRoute
  '/app/workspaces/$workspaceId/actions/$capId': typeof AppWorkspacesWorkspaceIdActionsCapIdRoute
  '/app/workspaces/$workspaceId/esg/frameworks': typeof AppWorkspacesWorkspaceIdEsgFrameworksRoute
  '/app/workspaces/$workspaceId/esg/requirements': typeof AppWorkspacesWorkspaceIdEsgRequirementsRoute
  '/app/workspaces/$workspaceId/esg/roadmap': typeof AppWorkspacesWorkspaceIdEsgRoadmapRoute
  '/app/workspaces/$workspaceId/evidence/$evidenceId': typeof AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute
  '/app/workspaces/$workspaceId/reports/$reportId': typeof AppWorkspacesWorkspaceIdReportsReportIdRoute
  '/app/workspaces/$workspaceId/actions/': typeof AppWorkspacesWorkspaceIdActionsIndexRoute
  '/app/workspaces/$workspaceId/evidence/': typeof AppWorkspacesWorkspaceIdEvidenceIndexRoute
  '/app/workspaces/$workspaceId/reports/': typeof AppWorkspacesWorkspaceIdReportsIndexRoute
  '/app/workspaces/$workspaceId/esg/implementation/$requirementId': typeof AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute
  '/app/workspaces/$workspaceId/governance/assessments/': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute
  '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/': typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/architecture'
    | '/assessment'
    | '/audit-log'
    | '/auth'
    | '/cip'
    | '/code-of-conduct'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/data-room'
    | '/demo'
    | '/evidence'
    | '/finance-triangulation'
    | '/findings'
    | '/frameworks'
    | '/guide'
    | '/help'
    | '/informal-economy'
    | '/institute'
    | '/issb-disclosures'
    | '/launch'
    | '/methodology'
    | '/obligations'
    | '/onboarding'
    | '/open-source'
    | '/pre-assessment'
    | '/privacy'
    | '/regulatory-compliance'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/vaults'
    | '/verify'
    | '/wallboard'
    | '/accept/$token'
    | '/admin/portfolio'
    | '/assessment/$frameworkId'
    | '/dashboard/trust-delta'
    | '/app/org/audit-log'
    | '/app/org/members'
    | '/app/org/settings'
    | '/app/workspaces/'
    | '/app/workspaces/$workspaceId/compliance-dashboard'
    | '/app/workspaces/$workspaceId/dashboard'
    | '/app/workspaces/$workspaceId/support-bot'
    | '/app/workspaces/$workspaceId/support-issues'
    | '/app/workspaces/$workspaceId/actions/$capId'
    | '/app/workspaces/$workspaceId/esg/frameworks'
    | '/app/workspaces/$workspaceId/esg/requirements'
    | '/app/workspaces/$workspaceId/esg/roadmap'
    | '/app/workspaces/$workspaceId/evidence/$evidenceId'
    | '/app/workspaces/$workspaceId/reports/$reportId'
    | '/app/workspaces/$workspaceId/actions/'
    | '/app/workspaces/$workspaceId/evidence/'
    | '/app/workspaces/$workspaceId/reports/'
    | '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
    | '/app/workspaces/$workspaceId/governance/assessments/'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/architecture'
    | '/assessment'
    | '/audit-log'
    | '/auth'
    | '/cip'
    | '/code-of-conduct'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/data-room'
    | '/demo'
    | '/evidence'
    | '/finance-triangulation'
    | '/findings'
    | '/frameworks'
    | '/guide'
    | '/help'
    | '/informal-economy'
    | '/institute'
    | '/issb-disclosures'
    | '/launch'
    | '/methodology'
    | '/obligations'
    | '/onboarding'
    | '/open-source'
    | '/pre-assessment'
    | '/privacy'
    | '/regulatory-compliance'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/vaults'
    | '/verify'
    | '/wallboard'
    | '/accept/$token'
    | '/admin/portfolio'
    | '/assessment/$frameworkId'
    | '/dashboard/trust-delta'
    | '/app/org/audit-log'
    | '/app/org/members'
    | '/app/org/settings'
    | '/app/workspaces'
    | '/app/workspaces/$workspaceId/compliance-dashboard'
    | '/app/workspaces/$workspaceId/dashboard'
    | '/app/workspaces/$workspaceId/support-bot'
    | '/app/workspaces/$workspaceId/support-issues'
    | '/app/workspaces/$workspaceId/actions/$capId'
    | '/app/workspaces/$workspaceId/esg/frameworks'
    | '/app/workspaces/$workspaceId/esg/requirements'
    | '/app/workspaces/$workspaceId/esg/roadmap'
    | '/app/workspaces/$workspaceId/evidence/$evidenceId'
    | '/app/workspaces/$workspaceId/reports/$reportId'
    | '/app/workspaces/$workspaceId/actions'
    | '/app/workspaces/$workspaceId/evidence'
    | '/app/workspaces/$workspaceId/reports'
    | '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
    | '/app/workspaces/$workspaceId/governance/assessments'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/architecture'
    | '/assessment'
    | '/audit-log'
    | '/auth'
    | '/cip'
    | '/code-of-conduct'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/data-room'
    | '/demo'
    | '/evidence'
    | '/finance-triangulation'
    | '/findings'
    | '/frameworks'
    | '/guide'
    | '/help'
    | '/informal-economy'
    | '/institute'
    | '/issb-disclosures'
    | '/launch'
    | '/methodology'
    | '/obligations'
    | '/onboarding'
    | '/open-source'
    | '/pre-assessment'
    | '/privacy'
    | '/regulatory-compliance'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/vaults'
    | '/verify'
    | '/wallboard'
    | '/accept/$token'
    | '/admin_/portfolio'
    | '/assessment/$frameworkId'
    | '/dashboard_/trust-delta'
    | '/app/org/audit-log'
    | '/app/org/members'
    | '/app/org/settings'
    | '/app/workspaces/'
    | '/app/workspaces/$workspaceId/compliance-dashboard'
    | '/app/workspaces/$workspaceId/dashboard'
    | '/app/workspaces/$workspaceId/support-bot'
    | '/app/workspaces/$workspaceId/support-issues'
    | '/app/workspaces/$workspaceId/actions/$capId'
    | '/app/workspaces/$workspaceId/esg/frameworks'
    | '/app/workspaces/$workspaceId/esg/requirements'
    | '/app/workspaces/$workspaceId/esg/roadmap'
    | '/app/workspaces/$workspaceId/evidence/$evidenceId'
    | '/app/workspaces/$workspaceId/reports/$reportId'
    | '/app/workspaces/$workspaceId/actions/'
    | '/app/workspaces/$workspaceId/evidence/'
    | '/app/workspaces/$workspaceId/reports/'
    | '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
    | '/app/workspaces/$workspaceId/governance/assessments/'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
    | '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssessmentRoute: typeof AssessmentRouteWithChildren
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  CipRoute: typeof CipRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DataRoomRoute: typeof DataRoomRoute
  DemoRoute: typeof DemoRoute
  EvidenceRoute: typeof EvidenceRoute
  FinanceTriangulationRoute: typeof FinanceTriangulationRoute
  FindingsRoute: typeof FindingsRoute
  FrameworksRoute: typeof FrameworksRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  InformalEconomyRoute: typeof InformalEconomyRoute
  InstituteRoute: typeof InstituteRoute
  IssbDisclosuresRoute: typeof IssbDisclosuresRoute
  LaunchRoute: typeof LaunchRoute
  MethodologyRoute: typeof MethodologyRoute
  ObligationsRoute: typeof ObligationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PreAssessmentRoute: typeof PreAssessmentRoute
  PrivacyRoute: typeof PrivacyRoute
  RegulatoryComplianceRoute: typeof RegulatoryComplianceRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  VaultsRoute: typeof VaultsRoute
  VerifyRoute: typeof VerifyRoute
  WallboardRoute: typeof WallboardRoute
  AcceptTokenRoute: typeof AcceptTokenRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  DashboardTrustDeltaRoute: typeof DashboardTrustDeltaRoute
  AppOrgAuditLogRoute: typeof AppOrgAuditLogRoute
  AppOrgMembersRoute: typeof AppOrgMembersRoute
  AppOrgSettingsRoute: typeof AppOrgSettingsRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppWorkspacesWorkspaceIdComplianceDashboardRoute: typeof AppWorkspacesWorkspaceIdComplianceDashboardRoute
  AppWorkspacesWorkspaceIdDashboardRoute: typeof AppWorkspacesWorkspaceIdDashboardRoute
  AppWorkspacesWorkspaceIdSupportBotRoute: typeof AppWorkspacesWorkspaceIdSupportBotRoute
  AppWorkspacesWorkspaceIdSupportIssuesRoute: typeof AppWorkspacesWorkspaceIdSupportIssuesRoute
  AppWorkspacesWorkspaceIdActionsCapIdRoute: typeof AppWorkspacesWorkspaceIdActionsCapIdRoute
  AppWorkspacesWorkspaceIdEsgFrameworksRoute: typeof AppWorkspacesWorkspaceIdEsgFrameworksRoute
  AppWorkspacesWorkspaceIdEsgRequirementsRoute: typeof AppWorkspacesWorkspaceIdEsgRequirementsRoute
  AppWorkspacesWorkspaceIdEsgRoadmapRoute: typeof AppWorkspacesWorkspaceIdEsgRoadmapRoute
  AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute: typeof AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute
  AppWorkspacesWorkspaceIdReportsReportIdRoute: typeof AppWorkspacesWorkspaceIdReportsReportIdRoute
  AppWorkspacesWorkspaceIdActionsIndexRoute: typeof AppWorkspacesWorkspaceIdActionsIndexRoute
  AppWorkspacesWorkspaceIdEvidenceIndexRoute: typeof AppWorkspacesWorkspaceIdEvidenceIndexRoute
  AppWorkspacesWorkspaceIdReportsIndexRoute: typeof AppWorkspacesWorkspaceIdReportsIndexRoute
  AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute: typeof AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute
  AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cip': {
      id: '/cip'
      path: '/cip'
      fullPath: '/cip'
      preLoaderRoute: typeof CipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-room': {
      id: '/data-room'
      path: '/data-room'
      fullPath: '/data-room'
      preLoaderRoute: typeof DataRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-triangulation': {
      id: '/finance-triangulation'
      path: '/finance-triangulation'
      fullPath: '/finance-triangulation'
      preLoaderRoute: typeof FinanceTriangulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informal-economy': {
      id: '/informal-economy'
      path: '/informal-economy'
      fullPath: '/informal-economy'
      preLoaderRoute: typeof InformalEconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute': {
      id: '/institute'
      path: '/institute'
      fullPath: '/institute'
      preLoaderRoute: typeof InstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issb-disclosures': {
      id: '/issb-disclosures'
      path: '/issb-disclosures'
      fullPath: '/issb-disclosures'
      preLoaderRoute: typeof IssbDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligations': {
      id: '/obligations'
      path: '/obligations'
      fullPath: '/obligations'
      preLoaderRoute: typeof ObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-assessment': {
      id: '/pre-assessment'
      path: '/pre-assessment'
      fullPath: '/pre-assessment'
      preLoaderRoute: typeof PreAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-compliance': {
      id: '/regulatory-compliance'
      path: '/regulatory-compliance'
      fullPath: '/regulatory-compliance'
      preLoaderRoute: typeof RegulatoryComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallboard': {
      id: '/wallboard'
      path: '/wallboard'
      fullPath: '/wallboard'
      preLoaderRoute: typeof WallboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept/$token': {
      id: '/accept/$token'
      path: '/accept/$token'
      fullPath: '/accept/$token'
      preLoaderRoute: typeof AcceptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/portfolio': {
      id: '/admin_/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$frameworkId': {
      id: '/assessment/$frameworkId'
      path: '/$frameworkId'
      fullPath: '/assessment/$frameworkId'
      preLoaderRoute: typeof AssessmentFrameworkIdRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/dashboard_/trust-delta': {
      id: '/dashboard_/trust-delta'
      path: '/dashboard/trust-delta'
      fullPath: '/dashboard/trust-delta'
      preLoaderRoute: typeof DashboardTrustDeltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/audit-log': {
      id: '/app/org/audit-log'
      path: '/app/org/audit-log'
      fullPath: '/app/org/audit-log'
      preLoaderRoute: typeof AppOrgAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/members': {
      id: '/app/org/members'
      path: '/app/org/members'
      fullPath: '/app/org/members'
      preLoaderRoute: typeof AppOrgMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/settings': {
      id: '/app/org/settings'
      path: '/app/org/settings'
      fullPath: '/app/org/settings'
      preLoaderRoute: typeof AppOrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/': {
      id: '/app/workspaces/'
      path: '/app/workspaces'
      fullPath: '/app/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/compliance-dashboard': {
      id: '/app/workspaces/$workspaceId/compliance-dashboard'
      path: '/app/workspaces/$workspaceId/compliance-dashboard'
      fullPath: '/app/workspaces/$workspaceId/compliance-dashboard'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdComplianceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/dashboard': {
      id: '/app/workspaces/$workspaceId/dashboard'
      path: '/app/workspaces/$workspaceId/dashboard'
      fullPath: '/app/workspaces/$workspaceId/dashboard'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/support-bot': {
      id: '/app/workspaces/$workspaceId/support-bot'
      path: '/app/workspaces/$workspaceId/support-bot'
      fullPath: '/app/workspaces/$workspaceId/support-bot'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSupportBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/support-issues': {
      id: '/app/workspaces/$workspaceId/support-issues'
      path: '/app/workspaces/$workspaceId/support-issues'
      fullPath: '/app/workspaces/$workspaceId/support-issues'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSupportIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/actions/': {
      id: '/app/workspaces/$workspaceId/actions/'
      path: '/app/workspaces/$workspaceId/actions'
      fullPath: '/app/workspaces/$workspaceId/actions/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/actions/$capId': {
      id: '/app/workspaces/$workspaceId/actions/$capId'
      path: '/app/workspaces/$workspaceId/actions/$capId'
      fullPath: '/app/workspaces/$workspaceId/actions/$capId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdActionsCapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/esg/frameworks': {
      id: '/app/workspaces/$workspaceId/esg/frameworks'
      path: '/app/workspaces/$workspaceId/esg/frameworks'
      fullPath: '/app/workspaces/$workspaceId/esg/frameworks'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEsgFrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/esg/requirements': {
      id: '/app/workspaces/$workspaceId/esg/requirements'
      path: '/app/workspaces/$workspaceId/esg/requirements'
      fullPath: '/app/workspaces/$workspaceId/esg/requirements'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEsgRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/esg/roadmap': {
      id: '/app/workspaces/$workspaceId/esg/roadmap'
      path: '/app/workspaces/$workspaceId/esg/roadmap'
      fullPath: '/app/workspaces/$workspaceId/esg/roadmap'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEsgRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/evidence/': {
      id: '/app/workspaces/$workspaceId/evidence/'
      path: '/app/workspaces/$workspaceId/evidence'
      fullPath: '/app/workspaces/$workspaceId/evidence/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/evidence/$evidenceId': {
      id: '/app/workspaces/$workspaceId/evidence/$evidenceId'
      path: '/app/workspaces/$workspaceId/evidence/$evidenceId'
      fullPath: '/app/workspaces/$workspaceId/evidence/$evidenceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEvidenceEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/reports/': {
      id: '/app/workspaces/$workspaceId/reports/'
      path: '/app/workspaces/$workspaceId/reports'
      fullPath: '/app/workspaces/$workspaceId/reports/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/reports/$reportId': {
      id: '/app/workspaces/$workspaceId/reports/$reportId'
      path: '/app/workspaces/$workspaceId/reports/$reportId'
      fullPath: '/app/workspaces/$workspaceId/reports/$reportId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/esg/implementation/$requirementId': {
      id: '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
      path: '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
      fullPath: '/app/workspaces/$workspaceId/esg/implementation/$requirementId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/governance/assessments/': {
      id: '/app/workspaces/$workspaceId/governance/assessments/'
      path: '/app/workspaces/$workspaceId/governance/assessments'
      fullPath: '/app/workspaces/$workspaceId/governance/assessments/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/': {
      id: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/'
      path: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId'
      fullPath: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review': {
      id: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
      path: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
      fullPath: '/app/workspaces/$workspaceId/governance/assessments/$assessmentId/review'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessmentRouteChildren {
  AssessmentFrameworkIdRoute: typeof AssessmentFrameworkIdRoute
}

const AssessmentRouteChildren: AssessmentRouteChildren = {
  AssessmentFrameworkIdRoute: AssessmentFrameworkIdRoute,
}

const AssessmentRouteWithChildren = AssessmentRoute._addFileChildren(
  AssessmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssessmentRoute: AssessmentRouteWithChildren,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  CipRoute: CipRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DataRoomRoute: DataRoomRoute,
  DemoRoute: DemoRoute,
  EvidenceRoute: EvidenceRoute,
  FinanceTriangulationRoute: FinanceTriangulationRoute,
  FindingsRoute: FindingsRoute,
  FrameworksRoute: FrameworksRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  InformalEconomyRoute: InformalEconomyRoute,
  InstituteRoute: InstituteRoute,
  IssbDisclosuresRoute: IssbDisclosuresRoute,
  LaunchRoute: LaunchRoute,
  MethodologyRoute: MethodologyRoute,
  ObligationsRoute: ObligationsRoute,
  OnboardingRoute: OnboardingRoute,
  OpenSourceRoute: OpenSourceRoute,
  PreAssessmentRoute: PreAssessmentRoute,
  PrivacyRoute: PrivacyRoute,
  RegulatoryComplianceRoute: RegulatoryComplianceRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  VaultsRoute: VaultsRoute,
  VerifyRoute: VerifyRoute,
  WallboardRoute: WallboardRoute,
  AcceptTokenRoute: AcceptTokenRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  DashboardTrustDeltaRoute: DashboardTrustDeltaRoute,
  AppOrgAuditLogRoute: AppOrgAuditLogRoute,
  AppOrgMembersRoute: AppOrgMembersRoute,
  AppOrgSettingsRoute: AppOrgSettingsRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppWorkspacesWorkspaceIdComplianceDashboardRoute:
    AppWorkspacesWorkspaceIdComplianceDashboardRoute,
  AppWorkspacesWorkspaceIdDashboardRoute:
    AppWorkspacesWorkspaceIdDashboardRoute,
  AppWorkspacesWorkspaceIdSupportBotRoute:
    AppWorkspacesWorkspaceIdSupportBotRoute,
  AppWorkspacesWorkspaceIdSupportIssuesRoute:
    AppWorkspacesWorkspaceIdSupportIssuesRoute,
  AppWorkspacesWorkspaceIdActionsCapIdRoute:
    AppWorkspacesWorkspaceIdActionsCapIdRoute,
  AppWorkspacesWorkspaceIdEsgFrameworksRoute:
    AppWorkspacesWorkspaceIdEsgFrameworksRoute,
  AppWorkspacesWorkspaceIdEsgRequirementsRoute:
    AppWorkspacesWorkspaceIdEsgRequirementsRoute,
  AppWorkspacesWorkspaceIdEsgRoadmapRoute:
    AppWorkspacesWorkspaceIdEsgRoadmapRoute,
  AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute:
    AppWorkspacesWorkspaceIdEvidenceEvidenceIdRoute,
  AppWorkspacesWorkspaceIdReportsReportIdRoute:
    AppWorkspacesWorkspaceIdReportsReportIdRoute,
  AppWorkspacesWorkspaceIdActionsIndexRoute:
    AppWorkspacesWorkspaceIdActionsIndexRoute,
  AppWorkspacesWorkspaceIdEvidenceIndexRoute:
    AppWorkspacesWorkspaceIdEvidenceIndexRoute,
  AppWorkspacesWorkspaceIdReportsIndexRoute:
    AppWorkspacesWorkspaceIdReportsIndexRoute,
  AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute:
    AppWorkspacesWorkspaceIdEsgImplementationRequirementIdRoute,
  AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute:
    AppWorkspacesWorkspaceIdGovernanceAssessmentsIndexRoute,
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute:
    AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdReviewRoute,
  AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute:
    AppWorkspacesWorkspaceIdGovernanceAssessmentsAssessmentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
